branches:
    - main
    - master
plugins:
    - '@semantic-release/commit-analyzer'
    - '@semantic-release/release-notes-generator'
    - semantic-release-obsidian-plugin
    - - '@semantic-release/github'
      - assets:
            - path: main.js
            - path: manifest.json
            - path: styles.css
tagFormat: '${version}'
